### PR TITLE
Fix text submorphs

### PR DESCRIPTION
**Pull request by tylervernonsmith**
Quick fix (hopefully) for problem described in 699bbcf

(... plus a few other fixes)

### CODE REVIEW

**Comment by rksm** [comment]
@merryman OK to merge?

**Comment by merryman** [comment]
Yes, everything fine from my side.

**Comment by rksm** [comment]
It seems that the commits broke the tests? https://travis-ci.org/LivelyKernel/lively.morphic/builds/151306231

**Comment by tylervernonsmith** [comment]
Thanks @rksm, sorry for missing that-- fixed in 465001f9dbfb07f2e33a334a193bca8d13bd9bc1

**Pull request merged**
